### PR TITLE
Treats TimeOfDay-objects with same H/M/S truly as the same

### PR DESCRIPTION
**Pull request by Qqwy**
This PR ensures that two TimeOfDay-objects that have the same hour/minute/second fields are considered the same:

- Their `#inspect` will match.
- They can be used as keys in hashmaps. Before `#hash` and `#eql?` were overridden, two ToD-objects  would create two keys, even if they contained the same H/M/S.

### CODE REVIEW

**Comment by Qqwy** [comment]
The CI errors that are happening here seem to be caused by a requirement for an old bundler version or something, rather than problems with the implementation.

**Comment by donv** [comment]
Taking a look now.

**Comment by donv** [comment]
@Qqwy master is green now.  Can you rebase?

**Comment by donv** [comment]
@Qqwy Thanks!

**Pull request merged**
